const assert=require('node:assert/strict');const {chromium}=require('playwright');
const base='http://baltic-vending-solutions.local';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:true,acceptDownloads:true});const page=await context.newPage(),errors=[];let posts=0;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts++;});
 const open=async route=>{await page.goto(base+route,{waitUntil:'networkidle'});await page.waitForSelector('[data-model=ready]');await page.waitForSelector('.bvs-design-workbench:not([hidden])');await page.evaluate(()=>document.querySelector('.bvs-cookie-banner')?.remove());};
 const record=()=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('bvs-design-editor',1);r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts'),q=t.objectStore('drafts').get('smart-fridge');t.oncomplete=()=>{resolve(q.result);d.close();};};}));
 const saved=()=>page.waitForSelector('.bvs-design-save-status[data-state=saved]');
 const tool=async kind=>page.locator('[data-control=drawingTool]').selectOption(kind);
 const gesture=async points=>{await page.locator('.bvs-design-flat canvas').scrollIntoViewIfNeeded();const box=await page.locator('.bvs-design-flat canvas').boundingBox();await page.mouse.move(box.x+box.width*points[0][0],box.y+box.height*points[0][1]);await page.mouse.down();for(const [x,y] of points.slice(1))await page.mouse.move(box.x+box.width*x,box.y+box.height*y);await page.mouse.up();await saved();};
 await open('/en/design-editor/');await page.locator('[data-panel=left]').click();await page.locator('.bvs-design-drawing summary').click();
 const jitter=Array.from({length:21},(_,i)=>[.1+i*.035,.7+(i===0||i===20?0:i%2?.004:-.004)]);
 await page.locator('button[data-tool=draw]').click();await gesture(jitter);let draft=await record();assert.equal(draft.panels.left.strokes.length,1);assert.ok(draft.panels.left.strokes[0].points.length>10,'Raw keeps captured samples');
 await tool('smooth');await gesture(jitter);draft=await record();assert.equal(draft.panels.left.strokes[1].points.length,2,'Near straight smooth stroke becomes a line');
 const curve=Array.from({length:31},(_,i)=>[.1+i*.02,.45+Math.sin(i/30*Math.PI)*.1+(i%2?.002:-.002)]);await gesture(curve);draft=await record();assert.ok(draft.panels.left.strokes[2].points.length>2&&draft.panels.left.strokes[2].points.length<31,'Curve retains curvature with fewer shaky points');
 await tool('rectangle');await page.locator('[data-control=shapeFill]').check();await page.locator('[data-control=brushColour]').fill('#dd4400');await gesture([[.1,.1],[.8,.25]]);assert.deepEqual(await page.locator('.bvs-design-flat canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(200,180,1,1).data)),[221,68,0,255]);
 await tool('ellipse');await gesture([[.2,.3],[.8,.4]]);await tool('line');await gesture([[.1,.8],[.8,.9]]);
 await tool('text');await page.locator('[data-control=text]').fill('YOUR BRAND');await page.locator('[data-control=textSize]').fill('60');await gesture([[.1,.52]]);draft=await record();assert.equal(draft.panels.left.strokes.at(-1).text,'YOUR BRAND');assert.equal(draft.panels.left.strokes.at(-1).textSize,60);
 const count=draft.panels.left.strokes.length;await page.locator('[data-action=undo]').click();await saved();assert.equal((await record()).panels.left.strokes.length,count-1);await page.locator('[data-action=redo]').click();await saved();assert.equal((await record()).panels.left.strokes.length,count);
 await page.locator('.bvs-design-flat canvas').focus();await page.keyboard.press('Control+z');await saved();assert.equal((await record()).panels.left.strokes.length,count-1);await page.keyboard.press('Control+Shift+z');await saved();assert.equal((await record()).panels.left.strokes.length,count);
 // Real raycasts and pointer input on all three wrapping materials, no mocked viewer API.
 await tool('raw');
 for(const panel of ['front','left','right']){
  await page.locator(`[data-panel=${panel}]`).click();await page.locator('model-viewer').scrollIntoViewIfNeeded();await page.waitForTimeout(600);
  const hit=await page.evaluate(panel=>{const v=document.querySelector('model-viewer'),b=v.getBoundingClientRect();for(let y=b.top+40;y<b.bottom-20;y+=10)for(let x=b.left+20;x<b.right-20;x+=10){if(v.materialFromPoint(x,y)?.name!==`BVS wrap ${panel}`)continue;const h=v.positionAndNormalFromPoint(x,y);if(h?.uv?.u>.07&&h.uv.u<.25&&h.uv.v>.015&&h.uv.v<.09)return {x,y,uv:h.uv};}return null;},panel);
  assert.ok(hit,`Visible ${panel} wrap hit`);const before=(await record()).panels[panel].strokes.length;
  await page.locator('[data-preview-mode=draw]').click();assert.equal(await page.locator('model-viewer').evaluate(v=>v.cameraControls),false);
  await page.mouse.move(hit.x,hit.y);await page.mouse.down();await page.mouse.up();await saved();draft=await record();assert.equal(draft.panels[panel].strokes.length,before+1,`Draw on ${panel} machine`);
  const point=draft.panels[panel].strokes.at(-1).points[0];assert.ok(Math.abs(point.x-hit.uv.u)<.002&&Math.abs(point.y-hit.uv.v)<.002,'Ray UV matches flat panel');
  const pixel=await page.locator('.bvs-design-flat canvas').evaluate((c,p)=>Array.from(c.getContext('2d').getImageData(Math.floor(p.x*c.width),Math.floor(p.y*c.height),1,1).data),point);assert.deepEqual(pixel,[221,68,0,255],'3D drawing lands at matching flat coordinates');
  await page.locator('[data-preview-mode=rotate]').click();assert.equal(await page.locator('model-viewer').evaluate(v=>v.cameraControls),true);
 }
 // Clicking hardware must not paint through to a panel behind it.
 await page.locator('[data-panel=front]').click();await page.waitForTimeout(600);await page.locator('[data-preview-mode=draw]').click();const beforeHardware=(await record()).panels.front.strokes.length;
 const hardware=await page.evaluate(()=>{const v=document.querySelector('model-viewer'),b=v.getBoundingClientRect();for(let y=b.top+b.height*.3;y<b.bottom-30;y+=10)for(let x=b.left+20;x<b.right-20;x+=10){const m=v.materialFromPoint(x,y);if(m&&!m.name.startsWith('BVS wrap'))return {x,y};}});assert.ok(hardware);await page.mouse.click(hardware.x,hardware.y);assert.equal((await record()).panels.front.strokes.length,beforeHardware);
 await page.locator('[data-preview-mode=rotate]').click();const radius=await page.locator('model-viewer').evaluate(v=>v.getCameraOrbit().radius);await page.locator('[data-zoom=model-in]').click();await page.waitForTimeout(600);assert.ok(await page.locator('model-viewer').evaluate(v=>v.getCameraOrbit().radius)<radius);await page.locator('[data-action=view]').click();
 await page.locator('[data-panel=left]').click();await page.locator('.bvs-design-flat canvas').scrollIntoViewIfNeeded();const normalWidth=(await page.locator('.bvs-design-flat canvas').boundingBox()).width;await page.locator('[data-zoom=flat-in]').click();await page.locator('[data-zoom=flat-in]').click();assert.ok((await page.locator('.bvs-design-flat canvas').boundingBox()).width>normalWidth*1.3);
 const modelFile=await page.evaluate(async()=>{const f=await document.querySelector('.bvs-quote-form').bvsEditorDesign.file();const image=await createImageBitmap(f),c=document.createElement('canvas');c.width=image.width;c.height=image.height;c.getContext('2d').drawImage(image,0,0);const pixel=[...c.getContext('2d').getImageData(1170,270,1,1).data];image.close();return {type:f.type,size:f.size,pixel};});assert.equal(modelFile.type,'image/png');assert.ok(modelFile.size>5000);assert.deepEqual(modelFile.pixel,[221,68,0,255],'Generated enquiry PNG includes the filled rectangle');
 await saved();const drawings=(await record()).panels;await open('/dizaina-redaktors/');await saved();assert.deepEqual((await record()).panels,drawings,'Shapes, text and strokes restored in the other language');assert.equal(await page.locator('[data-flat-zoom]').innerText(),'150%');assert.equal(await page.locator('.bvs-editor-design-option').isVisible(),true);
 // Touch gesture on a zoomed flat panel, then mobile reflow and both language labels.
 await page.setViewportSize({width:375,height:900});await tool('ellipse');await page.locator('.bvs-design-flat').scrollIntoViewIfNeeded();const touchBox=await page.locator('.bvs-design-flat canvas').boundingBox(),touch=await context.newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchBox.x+touchBox.width*.1,y:touchBox.y+touchBox.height*.1}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchBox.x+touchBox.width*.35,y:touchBox.y+touchBox.height*.2}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await saved();assert.equal((await record()).panels.left.strokes.at(-1).kind,'ellipse');const prior=(await record()).panels.left.strokes.length;await page.locator('[data-action=pan-panel]').click();await page.locator('.bvs-design-flat').scrollIntoViewIfNeeded();const viewport=await page.locator('.bvs-design-canvas-wrap').boundingBox();await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:viewport.x+viewport.width*.75,y:viewport.y+viewport.height*.65}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:viewport.x+viewport.width*.4,y:viewport.y+viewport.height*.4}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const scroll=await page.locator('.bvs-design-canvas-wrap').evaluate(e=>({x:e.scrollLeft,y:e.scrollTop}));assert.ok(scroll.x>10&&scroll.y>10,'Touch pan reaches zoomed panel areas');assert.equal((await record()).panels.left.strokes.length,prior,'Panning never draws');await page.locator('[data-action=pan-panel]').click();assert.equal(await page.locator('[data-action=pan-panel]').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.bvs-design-flat').evaluate(e=>getComputedStyle(e).position),'sticky');assert.ok((await page.locator('[data-control=brushSize]').evaluate(e=>e.getBoundingClientRect().height))>=44);assert.ok((await page.locator('.bvs-design-drawing summary').boundingBox()).height>=44);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('[data-preview-mode=draw]').textContent(),'Zīmēt uz iekārtas');
 assert.deepEqual(errors,[]);assert.equal(posts,0);assert.deepEqual(await context.cookies(),[]);
 console.log('PASS: raw/smooth strokes, line/rectangle/ellipse/text, undo/redo and shortcuts, actual 3D painting on all panels, protected hardware, machine/panel zoom, restored drawings across languages, PNG enquiry export, mobile touch drawing/panning, sticky editing and 44px targets, no draft uploads or page errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
