const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {chromium}=require('playwright');
const base='http://baltic-vending-solutions.local',profile=fs.mkdtempSync(path.join(os.tmpdir(),'bvs-design-draft-'));
(async()=>{let context;const errors=[];let uploads=0;
const launch=async()=>{context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1440,height:1100}});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.method()==='POST')uploads++;});return page;};
const open=async(page,route)=>{await page.goto(base+route,{waitUntil:'networkidle'});await page.waitForSelector('.bvs-design-workbench:not([hidden])');await page.evaluate(()=>document.querySelector('.bvs-cookie-banner')?.remove());};
const colour=async(page,value)=>{await page.locator('[data-control=hex]').fill(value);await page.locator('[data-control=hex]').dispatchEvent('change');};
const saved=async page=>page.waitForSelector('.bvs-design-save-status[data-state=saved]');
const record=async page=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('bvs-design-editor',1);r.onsuccess=()=>{const db=r.result,transaction=db.transaction('drafts','readonly'),request=transaction.objectStore('drafts').get('smart-fridge');transaction.oncomplete=()=>{db.close();const draft=request.result;if(draft)draft.panels=Object.fromEntries(Object.entries(draft.panels).map(([name,p])=>[name,{...p,artwork:p.artwork?{type:p.artwork.type,size:p.artwork.size}:null,logo:p.logo?{type:p.logo.type,size:p.logo.size}:null}]));resolve(draft);};transaction.onerror=()=>reject(transaction.error);};}));
try{
 let page=await launch();await open(page,'/en/design-editor/');assert.equal(await record(page),undefined,'Untouched editor stores no design');
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=100;const x=c.getContext('2d');x.fillStyle='#ffb133';x.fillRect(0,0,200,100);x.fillStyle='#16282d';x.font='bold 30px sans-serif';x.fillText('BRAND',20,65);return c.toDataURL().split(',')[1];});
 await colour(page,'#a03c25');await page.locator('[data-upload=artwork]').setInputFiles({name:'front-art.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForSelector('.bvs-design-fit:not([hidden])');await page.locator('[data-control=fit]').selectOption('contain');
 await page.locator('[data-upload=logo]').setInputFiles({name:'front-logo.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForSelector('.bvs-design-logo-controls:not([hidden])');await page.locator('[data-control=size]').fill('45');await page.locator('[data-control=size]').dispatchEvent('input');
 await page.locator('[data-panel=left]').click();await colour(page,'#88bb11');
 await page.locator('[data-panel=right]').click();await colour(page,'#243dee');await page.locator('[data-upload=logo]').setInputFiles({name:'side-logo.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForSelector('.bvs-design-logo-controls:not([hidden])');
 for(const [control,value] of [['size','40'],['x','60'],['y','30'],['rotation','15']]){await page.locator(`[data-control=${control}]`).fill(value);await page.locator(`[data-control=${control}]`).dispatchEvent('input');}
 await page.locator('.bvs-design-drawing summary').click();await page.locator('button[data-tool=draw]').click();await page.locator('[data-control=brushColour]').fill('#ffef00');await page.locator('[data-control=brushColour]').dispatchEvent('input');await page.locator('[data-control=brushSize]').fill('18');await page.locator('[data-control=brushSize]').dispatchEvent('input');
 await page.locator('.bvs-design-flat canvas').scrollIntoViewIfNeeded();const box=await page.locator('.bvs-design-flat canvas').boundingBox();await page.mouse.move(box.x+box.width*.1,box.y+box.height*.7);await page.mouse.down();await page.mouse.move(box.x+box.width*.8,box.y+box.height*.7,{steps:12});await page.mouse.up();
 await page.locator('[name=name]').fill('This contact detail must not be saved');await saved(page);const canvasBefore=await page.locator('.bvs-design-flat canvas').evaluate(c=>c.toDataURL());
 const draft=await record(page);assert.equal(draft.selected,'right');assert.equal(draft.panels.right.strokes.length,1);assert.equal(draft.panels.front.artwork.type,'image/png');assert.ok(!JSON.stringify(draft).includes('This contact detail'));assert.equal(uploads,0);assert.deepEqual(await context.cookies(),[]);
 // Close the browser process and reopen the same profile in the other language.
 await context.close();page=await launch();await open(page,'/dizaina-redaktors/');await saved(page);assert.match(await page.locator('.bvs-design-save-status').innerText(),/atjaunots/);assert.equal(await page.locator('[data-control=hex]').inputValue(),'#243dee');assert.equal(await page.locator('[data-control=size]').inputValue(),'40');assert.equal(await page.locator('[data-control=x]').inputValue(),'60');assert.equal(await page.locator('[data-control=rotation]').inputValue(),'15');assert.equal(await page.locator('[data-control=brushSize]').inputValue(),'18');assert.equal(await page.locator('button[data-tool=draw]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.bvs-design-flat canvas').evaluate(c=>c.toDataURL()),canvasBefore,'Logo and drawing pixels survive browser closure');assert.equal(await page.locator('[name=name]').inputValue(),'');assert.equal(await page.locator('.bvs-use-editor-design').isChecked(),true);assert.equal(await page.locator('.bvs-editor-design-option').isVisible(),true);
 await page.locator('[data-panel=front]').click();assert.equal(await page.locator('[data-control=hex]').inputValue(),'#a03c25');assert.equal(await page.locator('[data-control=fit]').inputValue(),'contain');assert.equal(await page.locator('[data-file-label=artwork]').innerText(),'front-art.png');assert.equal(await page.locator('[data-control=size]').inputValue(),'45');assert.equal(await page.locator('.bvs-design-flat canvas').evaluate(c=>c.getContext('2d').getImageData(400,400,1,1).data[3]),0);await page.locator('[data-panel=left]').click();assert.equal(await page.locator('[data-control=hex]').inputValue(),'#88bb11');
 // Navigation immediately after an edit flushes the pending autosave.
 await colour(page,'#9911aa');await page.reload({waitUntil:'networkidle'});await page.waitForSelector('.bvs-design-workbench:not([hidden])');assert.equal(await page.locator('[data-control=hex]').inputValue(),'#9911aa');
 await page.setViewportSize({width:375,height:900});await page.locator('.bvs-design-save-status').screenshot({path:'output/design-draft-saved-lv-375.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 page.once('dialog',dialog=>dialog.accept());await page.locator('[data-action=reset]').click();await page.waitForSelector('.bvs-design-save-status[data-state=empty]');assert.equal(await record(page),undefined);await page.reload({waitUntil:'networkidle'});await page.waitForSelector('.bvs-design-workbench:not([hidden])');assert.equal(await page.locator('[data-control=hex]').inputValue(),(await page.locator('[data-control=colour]').getAttribute('value')).toLowerCase());assert.equal(await page.locator('.bvs-editor-design-option').isVisible(),false);
 // Storage failures are visible and editing remains usable.
 const blocked=await context.newPage();await blocked.addInitScript(()=>Object.defineProperty(window,'indexedDB',{value:{open(){throw new DOMException('Blocked','SecurityError');}}}));await open(blocked,'/en/design-editor/');await blocked.waitForSelector('.bvs-design-save-status[data-state=error]');await colour(blocked,'#883322');await blocked.waitForSelector('.bvs-design-save-status[data-state=error]');assert.equal(await blocked.locator('[data-control=hex]').inputValue(),'#883322');await blocked.close();
 await page.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('Full','QuotaExceededError');};});await colour(page,'#114488');await page.waitForSelector('.bvs-design-save-status[data-state=error]');assert.equal(uploads,0);assert.deepEqual(errors,[]);
 console.log('PASS: one IndexedDB draft retains panel colours, PNG artwork/logos, layout, drawing and tool state across browser closure and languages; contact details excluded, pending saves flushed on navigation, automatic form attachment available after restore, reset deletes draft, blocked/full storage handled, mobile reflow and no upload requests.');
}finally{if(context)await context.close();fs.rmSync(profile,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exit(1);});
