const assert=require('node:assert/strict'),{chromium}=require('playwright');
const base='http://baltic-vending-solutions.local';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:true}),page=await context.newPage(),errors=[];let posts=0;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts++;});
 const open=async route=>{await page.goto(base+route,{waitUntil:'networkidle'});await page.waitForSelector('[data-model=ready]');await page.waitForSelector('.bvs-design-workbench:not([hidden])');await page.evaluate(()=>document.querySelector('.bvs-cookie-banner')?.remove());};
 const record=()=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('bvs-design-editor',1);r.onsuccess=()=>{const d=r.result,t=d.transaction('drafts'),q=t.objectStore('drafts').get('smart-fridge');t.oncomplete=()=>{resolve(q.result);d.close();};};}));
 const saved=()=>page.waitForSelector('.bvs-design-save-status[data-state=saved]');
 const choose=async kind=>{if(kind==='erase'){await page.locator('[data-action=eraser]').click();assert.equal(await page.locator('[data-action=eraser]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-control=drawingTool]').inputValue(),'erase');}else await page.locator('[data-control=drawingTool]').selectOption(kind);};
 const gesture=async points=>{const c=page.locator('.bvs-design-flat canvas');await c.scrollIntoViewIfNeeded();const b=await c.boundingBox();await page.mouse.move(b.x+b.width*points[0][0],b.y+b.height*points[0][1]);await page.mouse.down();for(const [x,y] of points.slice(1))await page.mouse.move(b.x+b.width*x,b.y+b.height*y);await page.mouse.up();await saved();};
 await open('/en/design-editor/');await page.locator('button[data-panel=left]').click();await page.locator('.bvs-design-drawing summary').click();
 for(const kind of ['raw','smooth','line','rectangle','ellipse','text']){
  await choose(kind);if(['rectangle','ellipse'].includes(kind))await page.locator('[data-control=shapeFill]').check();if(kind==='text'){await page.locator('[data-control=text]').fill('DELETE');await page.locator('[data-control=textSize]').fill('60');}
  await gesture(kind==='text'?[[.1,.2]]:['rectangle','ellipse'].includes(kind)?[[.2,.2],[.8,.4]]:[[.2,.7],[.4,.71],[.6,.7],[.8,.7]]);assert.equal((await record()).panels.left.strokes.length,1);
  const pixel=await page.locator('.bvs-design-flat canvas').evaluate(c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let i=0;i<a.length;i+=4)if(a[i]>245&&a[i+1]>245&&a[i+2]>245&&a[i+3])return [(i/4%c.width+.5)/c.width,(Math.floor(i/4/c.width)+.5)/c.height];});assert.ok(pixel,kind+' painted pixels');
  await choose('erase');assert.equal(await page.locator('[data-preview-mode=draw]').innerText(),'Erase on machine');assert.equal(await page.locator('[data-control=brushColour]').isVisible(),false);await gesture([pixel]);assert.equal((await record()).panels.left.strokes.length,0,kind+' erased');
  await page.locator('[data-action=undo]').click();await saved();assert.equal((await record()).panels.left.strokes.length,1);await page.locator('[data-action=redo]').click();await saved();assert.equal((await record()).panels.left.strokes.length,0);
 }
 // Overlap removes only the topmost item. Blank clicks preserve a pending redo.
 for(const colour of ['#ffffff','#ff0000']){await choose('line');await page.locator('[data-control=brushColour]').fill(colour);await gesture([[.2,.5],[.8,.5]]);}
 await choose('erase');await gesture([[.5,.5]]);assert.equal((await record()).panels.left.strokes.length,1);assert.equal((await record()).panels.left.strokes[0].colour,'#ffffff');await page.locator('[data-action=undo]').click();await saved();await gesture([[.9,.9]]);assert.equal(await page.locator('[data-action=redo]').isEnabled(),true);await page.locator('[data-action=redo]').click();await saved();
 // Transparent logo pixels expose the line underneath; rotated painted logo pixels remain hittable.
 const logo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=100;c.getContext('2d').fillRect(0,0,25,100);return c.toDataURL().split(',')[1];});await page.locator('[data-upload=logo]').setInputFiles({name:'transparent.png',mimeType:'image/png',buffer:Buffer.from(logo,'base64')});await page.waitForSelector('.bvs-design-logo-controls:not([hidden])');
 for(const [key,value] of Object.entries({size:40,x:50,y:50})){await page.locator(`[data-control=${key}]`).fill(String(value));await page.locator(`[data-control=${key}]`).dispatchEvent('input');await page.locator(`[data-control=${key}]`).dispatchEvent('change');}
 await gesture([[.5,.5]]);assert.equal((await record()).panels.left.strokes.length,0);assert.ok((await record()).panels.left.logo,'Transparent centre does not delete logo');await page.locator('[data-control=rotation]').fill('45');await page.locator('[data-control=rotation]').dispatchEvent('input');await page.locator('[data-control=rotation]').dispatchEvent('change');await gesture([[.394,.459]]);assert.equal((await record()).panels.left.logo,null);await page.locator('[data-action=undo]').click();await saved();assert.ok((await record()).panels.left.logo);await page.locator('[data-action=redo]').click();await saved();
 // Actual 3D raycast drawing and erasing on each wrap panel, plus protected hardware.
 for(const panel of ['front','left','right']){
  await page.locator('button[data-panel='+panel+']').click();await choose('raw');await page.locator('model-viewer').scrollIntoViewIfNeeded();await page.waitForTimeout(600);
  const hit=await page.evaluate(panel=>{const v=document.querySelector('model-viewer'),b=v.getBoundingClientRect();for(let y=b.top+40;y<b.bottom-20;y+=8)for(let x=b.left+20;x<b.right-20;x+=8){if(v.materialFromPoint(x,y)?.name!==`BVS wrap ${panel}`)continue;const h=v.positionAndNormalFromPoint(x,y);if(h?.uv?.u>.07&&h.uv.u<.25&&h.uv.v>.015&&h.uv.v<.09)return {x,y};}return null;},panel);assert.ok(hit,panel+' raycast');await page.locator('[data-preview-mode=draw]').click();await page.mouse.click(hit.x,hit.y);await saved();assert.equal((await record()).panels[panel].strokes.length,1);
  await choose('erase');await page.mouse.click(hit.x,hit.y);await saved();assert.equal((await record()).panels[panel].strokes.length,0,panel+' machine erase');await page.locator('[data-action=undo]').click();await saved();
  const hardware=await page.evaluate(()=>{const v=document.querySelector('model-viewer'),b=v.getBoundingClientRect();for(let y=b.top+60;y<b.bottom-20;y+=12)for(let x=b.left+20;x<b.right-20;x+=12){const m=v.materialFromPoint(x,y);if(m&&!m.name.startsWith('BVS wrap'))return {x,y};}return null;});assert.ok(hardware);await page.mouse.click(hardware.x,hardware.y);assert.equal(await page.locator('[data-action=redo]').isEnabled(),true);await page.locator('[data-action=redo]').click();await saved();await page.locator('[data-preview-mode=rotate]').click();
 }
 // Mobile touch erasure and cross-language reload of the selected tool and deletion.
 await choose('line');await gesture([[.2,.5],[.8,.5]]);await choose('erase');await page.setViewportSize({width:375,height:900});await page.locator('[data-action=preview-switch]').click();const c=page.locator('.bvs-design-flat canvas');await c.scrollIntoViewIfNeeded();const b=await c.boundingBox(),touch=await context.newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width*.5,y:b.y+b.height*.5}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await saved();assert.equal((await record()).panels.right.strokes.length,0);
 await open('/dizaina-redaktors/');assert.equal(await page.locator('[data-control=drawingTool]').inputValue(),'erase');assert.equal(await page.locator('[data-preview-mode=draw]').innerText(),'Dzēst uz iekārtas');assert.equal((await record()).panels.right.strokes.length,0);assert.deepEqual(errors,[]);assert.equal(posts,0);
 console.log('PASS: individual raw/smooth/line/shape/text deletion, topmost overlap, transparent/rotated logos, blank clicks and protected hardware,undo/redo,actual3D erasing on all panels,mobile touch and persisted bilingual eraser state,no uploads/page errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
